trigger:
  batch: true
  branches:
    include:
      - release
  paths:
    include:
      - "wonder-build-pipelines/"

pr: none

variables:
  - group: open-telemetry-ci-creds

stages:
  - stage: 'build_package'
    displayName: 'Build Package'
    dependsOn: []
    jobs:
      - job: build_package
        steps:
          - script: ./gradlew :javaagent:publishMavenJavaPublicationToMavenRepository
            env:
              MAVEN_ACCESS_TOKEN: $(maven-package-token)
            displayName: 'Build Package'
